version: "3.2"
services:
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass 
      - MYSQL_DATABASE=practice_db
    container_name: mysql-app
    ports:
        - "3306:3306"
  adminer:
    image: adminer
    networks: 
      - backend
    ports:
      - "8080:8080"
networks:
  backend: